deck_schema = [
    "decklist_id",  # pk
    "player_name",
    "win_rate",
    "soul_differential",
    "n_wins",
    "n_losses",
    "n_cards",
    "m_count",
    "place",
    "offense",
    "defense",
]


metadata_tags = {
    "1": {"offense": "nativity", "defense": "herods"},
    "2": {"offense": "nativity", "defense": "herods"},
    "3": {"offense": "nativity", "defense": "thieves"},
    "4": {"offense": "clay", "defense": "herods"},
    "5": {"offense": "clay", "defense": "herods"},
    "6": {"offense": "clay", "defense": "black/gray"},
    "7": {"offense": "clay", "defense": "herods"},
    "8": {"offense": "daniel", "defense": "demons"},
    "9": {"offense": "clay", "defense": "thieves"},
    "10": {"offense": "priests", "defense": "black"},
    "11": {"offense": "nativity", "defense": "black/gray"},
    "12": {"offense": "nativity", "defense": "black/gray"},
    "13": {"offense": "daniel", "defense": "demons"},
    "14": {"offense": "blue", "defense": "pale green"},
    "15": {"offense": "clay", "defense": "thieves"},
    "16": {"offense": "clay", "defense": "black soul hide"},
    "17": {"offense": "nativity", "defense": "thieves"},
    "18": {"offense": "clay", "defense": "herods"},
    "19": {"offense": "nativity", "defense": "herods"},
    "20": {"offense": "clay", "defense": "herods"},
    "21": {"offense": "clay", "defense": "herods"},
    "22": {"offense": "clay", "defense": "herods"},
    "23": {"offense": "red", "defense": "black soul hide"},
    "24": {"offense": "clay", "defense": "black/gray soul hide"},
    "25": {"offense": "clay", "defense": "herods"},
    "26": {"offense": "clay", "defense": "herods"},
    "27": {"offense": "priests", "defense": "babylonians"},
    "28": {"offense": "blue", "defense": "pale green"},
    "29": {"offense": "clay", "defense": "herods"},
    "30": {"offense": "music leader", "defense": "black soul hide"},
    "31": {"offense": "clay", "defense": "misc"},
    "32": {"offense": "clay", "defense": "herods"},
    "33": {"offense": "silver", "defense": "demons"},
    "34": {"offense": "wilderness", "defense": "herods"},
    "35": {"offense": "purple", "defense": "black"},
    "36": {"offense": "clay", "defense": "herods"},
    "37": {"offense": "clay", "defense": "herods"},
    "38": {"offense": "silver", "defense": "gray"},
    "39": {"offense": "music leader", "defense": "gray"},
    "40": {"offense": "gold", "defense": "herods"},
    "41": {"offense": "nativity", "defense": "gray"},
    "42": {"offense": "blue", "defense": "black soul hide"},
    "43": {"offense": "gold", "defense": "herods"},
    "44": {"offense": "music leader", "defense": "black"},
    "45": {"offense": "nativity", "defense": "black soul hide"},
    "46": {"offense": "misc", "defense": "misc"},
    "47": {"offense": "gold", "defense": "thieves"},
    "48": {"offense": "music leader", "defense": "thieves"},
    "49": {"offense": "music leader", "defense": "misc"},
    "50": {"offense": "music leader", "defense": "demons"},
    "51": {"offense": "gold", "defense": "pale green"},
    "52": {"offense": "clay", "defense": "black"},
    "53": {"offense": "honeypot", "defense": "gray"},
    "54": {"offense": "clay", "defense": "herods"},
    "55": {"offense": "clay", "defense": "herods"},
    "56": {"offense": "music leader", "defense": "gray"},
    "57": {"offense": "misc", "defense": "demons"},
    "58": {"offense": "blue", "defense": "pale green"},
}
